testCases_to_run = { ...
      'CovarianceTest', ...
      'CovarianceGrammarTest', ...
      'GpModelTest', ...
      'HyperpriorsTest' ...
    };

fprintf('Running some tests. It might take a few seconds\n');
for i = 1:numel(testCases_to_run)
    eval(sprintf('run(%s);', testCases_to_run{i}))
end

test_hessians;